### ISSUE TITLE
Changing the key combination

### ISSUE THREAD

**Issue by liketoeatcheese** [HauntedBees/Godot-Project-File-Search-Addon#1]
Hey mate,

First of all, thank you for your gods work.

I wonder if there's a setting to change the key combination of the user's liking?

**Comment by HauntedBees** [comment]
The short answer is change the code on `search.gd::27` (https://github.com/HauntedBees/Godot-Project-File-Search-Addon/blob/39e9103eac16609b4c4e703a3ca9a3511c376f7d/addons/project_file_search/search.gd#L27).

The long answer is yeah I can definitely try to add a custom keybind setting within the next few days. I'm glad the add-on is useful for you!

**Comment by liketoeatcheese** [comment]
Thank you! No rush. But yea appreciate this
